POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoiaXNtYWlsMkBsaXZlLmNvbSIsImlhdCI6MTc0NDcyMDc5MiwiZXhwIjoxNzQ0NzI0MzkyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.J4u3q8AFgCZSssvZesYN93zie8x0myTBVrC1uXkk5U0
{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImlhdCI6MTc0NDcyMDc5MiwiZXhwIjoxNzQ0ODA3MTkyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.7g8921B3a9jyDzQ57i4BOQfyfxKNQgGB4DmgGgekHIM"
}